version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: kinder-denkspiele-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kinder-denkspiele
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
