version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: humanbenchmark-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: humanbenchmark
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
